language: ruby
rvm:
  - "1.9.3"
script: ruby --version

deploy:
  provider: heroku
  api_key:
    secure: 0VJm8s/Ir9pdKQOomaxOB1iiCFGwLlf5cO+tAGOBaUndYgtEe8fpzphi6QcCFBw1x5BZfBQlda8/SbJWQmKyBzbOfSAhKnjfCwz8+MIiU/oLBbXL6Xs6Q0LCdUp3QstTiq0xCR+Tn8Phm6kVZD+P3yWgX2OXO3WvBOQayAoHdbs=
  app: paas-profiles
  on:
    repo: stefan-kolb/paas-profiles
  run: "rake mongo:import"
