development:
  sessions:
    default:
      database: paas
      hosts:
          - localhost:27017

test:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URL'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>