development:
  sessions:
    default:
      database: paas
      hosts:
          - localhost:27017

test:
  sessions:
    default:
      database: paas_test
      hosts:
          - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>